# https://taskfile.dev

version: '2'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true

  docker:build:
    desc: _
    cmds:
      - docker build . -t jenmaster

  docker:run:
    desc: _
    cmds:
      - docker rm -f jenmaster_c
      - |
        docker run --name jenmaster_c \
        -p 8880:8880 \
        -p 58000:58000 \
        -v /Users/ivanne/jenkins_home:/var/jenkins_home \
        jenmaster

