# https://taskfile.dev

version: '2'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true

  docker:build:jenmaster:
    desc: _
    cmds:
      - docker build . -t jenmaster

  docker:build:jenconda:
    desc: _
    deps:
      - docker:build:jenmaster
    cmds:
      - docker build -f install.scripts/install-conda-in-docker.Dockerfile  -t jenconda install.scripts

  docker:build:
    desc: _
    deps:
      - docker:build:jenconda

  docker:run:
    desc: _
    cmds:
      - docker rm -f jenmaster_c jenconda || true
      - |
        docker run --name jenconda_c \
        -d \
        -p 8880:8080 \
        -p 58000:50000 \
        -v /Users/ivanne/jenkins_home:/var/jenkins_home \
        -v /var/run/docker.sock:/var/run/docker.sock \
        jenconda

  docker:clean:data:
    desc: _
    cmds:
      - rm -rf ~/jenkins_home/* ~/jenkins_home/.*

  install:jcli:
    desc: _
    cmds:
      - which brew && brew install jcli || true
      - |
        which brew \
        || curl -L https://github.com/jenkins-zh/jenkins-cli/releases/latest/download/jcli-linux-amd64.tar.gz|tar xzv \
        && sudo mv jcli /usr/local/bin/

  shapshot:update:
    desc: _
    cmds:
      - jcli plugin list > install.snapshots/snapshot_2020-05-20--00-40-45/jcli_plugin_list.org.tsv



