# https://taskfile.dev

version: '2.3'

vars:
  GREETING: E2E tests with docker-machine
  jentest_machine: {sh: cat cfg/_machine.name.txt}

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
      - task -l
    silent: true

  dm:list:
    desc: _
    cmds:
      - docker-machine ls

  tpa:
    desc: _
    cmds:
      - curl http://192.168.99.100:8880/
      - curl http://192.168.99.100:8880/ | grep 'Please wait while Jenkins is getting ready to work'




