# https://taskfile.dev

version: '3'
includes:
  maven: ./tasks/maven.tasks.yml

vars:
  _name_: project tasks

tasks:
  default:
    cmds:
      - echo "{{._name_}}"
      - task -l
    silent: true


