# https://taskfile.dev

version: '3'
includes:
  tbasic: test-basic.tasks.yml
vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
      - task -l
    silent: true
