# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!
  targets: >-
    dev-docs-local
    dev-editor-local
    local-dev-ring

tasks:
  apply:
    desc: |-
      goal: apply sematic task to target decks.
      sample: task apply task='show-urls'
    args: 
      task: taskname to dispatch 
      opts: taskgo runner options(--silent, etc) 
      params: task parameters
    vars:
      _spread_: true
      _with_items_: '{{.targets}}'
      _with_cmd_: task {{.opts}} {{.task}} {{.params}} -d
    cmds: 
      - echo '{{ regexReplaceAll " +" .targets "\n" }}' | xargs -I% {{._with_cmd_}} %

  stop-all:
    desc: stop all decks
    cmds: [{task: apply, vars: {task: spin-down }}]

  build-dev-dockers:
    desc: _
    cmds:
      - task: pull-proto-base-dockers
      - task: _build-dev-dockers

  pull-proto-base-dockers:
    desc: _
    vars:
      with_items: >-
        ubuntu:20.04
        jupyter/pyspark-notebook
        continuumio/miniconda3
        eeacms/jenkins-slave-dind:19.03-3.26-2
        jenkins/jenkins:2.272
        jenkins/jenkinsfile-runner
    cmds:
      - echo {{.with_items}}  | xargs -n1 -P4 docker pull 
     
  _build-dev-dockers:
    desc: stop all decks
    deps: 
  
    - task: apply
      vars: 
        task: build
        targets:  dev-docs-local
  
    - task: apply
      vars: 
        task: build
        targets: dev-editor-local
    cmds:
    - |-
      echo "dockers are ready"

  publish-dimgs:
    desc: publish docker images
    cmds:
      - task -d jenconda-dimg docker:publish