# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
      - task -l
    silent: true

  get-swarm-agent:
    desc: _
    cmds:
      - mkdir -p /tmp
      - cd /tmp && wget https://repo.jenkins-ci.org/releases/org/jenkins-ci/plugins/swarm-client/3.23/swarm-client-3.23.jar
      - mkdir -p /data/tools/
      - mv /tmp/swarm-client-3.23.jar /data/tools/
      
  run-jenw-on-host:
    desc: running jenkins on host
    cmds:
      - |
        java -jar /data/tools/swarm-client-3.23.jar \
        -master http://blade2:8080 \
        -labels 'sw-agent' \
        -fsroot '.' \
        -username jenworker \
        -password jenpassword
